---
meta: ~

name: (( .meta.deployment_name ))
director_uuid: (( .meta.director_uuid ))

releases: ~

compilation:
  workers: 2
  network: redis_z1
  reuse_compilation_vms: true
  cloud_properties: (( merge ))

update:
  canaries: 1
  canary_watch_time: 30000-180000
  update_watch_time: 30000-180000
  max_in_flight: 4

networks: (( merge ))

resource_pools: ~

jobs: ~

properties: (( merge ))
