---
meta:
  deployment_name: bosh-lite-redis
  director_uuid: de7e613b-0f3a-47f8-8e94-cbd81af62746
  release_name: cf-redis
  apps_domain: bosh-lite.com
  environment: bosh-lite
  external_domain: bosh-lite.com
  syslog_aggregator:
    address: 127.0.0.1
    port: 1234
  broker:
    name: redis
    username: admin
    password: admin
  cf:
    admin_username: admin
    admin_password: admin
    api_url: https://api.bosh-lite.com
    apps_domain: (( .meta.apps_domain ))
    nats:
      host: 10.244.0.6
      password: nats
      port: 4222
      username: nats
  service_name: redis
  route_name: redis-broker
  backups: #Leave this section empty if you don't require backups.
    access_key_id: YOUR_S3_ACCESS_KEY_ID
    secret_access_key: YOUR_S3_SECRET_ACCESS_KEY
    endpoint_url: S3_ENDPOINT_FOR_YOUR_REGION
    s3_region: S3_REGION
    bucket_name: YOUR_S3_BUCKET
    path: YOUR_S3_BACKUP_PATH
  redis:
    dedicated_plan:
      instance_count: 1
    shared_plan:
      instance_limit: 5
      max_memory: 262144000
    config_command: configalias
    save_command: anotherrandomstring
    bg_save_command: yetanotherrandomstring
